app:
  stt:
    credentials: classpath:stt-credentials.json

server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: "application/json,application/xml,text/html,text/xml,text/plain"
    min-response-size: 1024

spring:
  application:
    name: stt-experience-backend
  main:
    banner-mode: off
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    com.example.stt: INFO